//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class golf_order
    {
        public int id { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<int> golf_order_id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string des { get; set; }
        public Nullable<System.DateTime> from_date { get; set; }
        public Nullable<int> from_date_id { get; set; }
        public Nullable<System.DateTime> to_date { get; set; }
        public Nullable<int> to_date_id { get; set; }
        public Nullable<System.TimeSpan> from_time { get; set; }
        public Nullable<System.TimeSpan> to_time { get; set; }
    }
}
