//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class golf_order_package_stay
    {
        public int id { get; set; }
        public Nullable<int> golf_package_stay_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string full_details { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
