//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class golf_trophy
    {
        public int id { get; set; }
        public string name { get; set; }
        public string des { get; set; }
        public Nullable<decimal> price { get; set; }
        public string image { get; set; }
        public string banner { get; set; }
        public Nullable<int> golf_trophy_cat_id { get; set; }
    }
}
