//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GolfBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class slide
    {
        public int id { get; set; }
        public string image { get; set; }
        public string caption { get; set; }
        public string imagelink { get; set; }
        public string slogan { get; set; }
        public string link { get; set; }
        public string linktext { get; set; }
        public string type { get; set; }
        public Nullable<byte> deleted { get; set; }
    }
}
